import {
  FaceBookIcon,
  InstaGramIcon,
  TwitteRIcon,
  LinkedinIcon,
  YoutubeIcon,
  GlobeIcon,
  HeartIcon,
  GreaterThanIcon,
  CrossButtonIcon,
  StarIconLogo,
  InfoIconLogo,
  CrossButtonIconMob,
  CookieIconStyled,
} from "./IconStyles";
export {
  FaceBookIcon,
  InstaGramIcon,
  TwitteRIcon,
  LinkedinIcon,
  YoutubeIcon,
  GlobeIcon,
  HeartIcon,
  GreaterThanIcon,
  CrossButtonIcon,
  StarIconLogo,
  InfoIconLogo,
  CrossButtonIconMob,
  CookieIconStyled,
};
