import {
  FaceBookIcon,
  InstaGramIcon,
  TwitteRIcon,
  LinkedinIcon,
  YoutubeIcon,
  GlobeIcon,
  HeartIcon,
  GreaterThanIcon,
  CrossButtonIcon,
  StarIconLogo,
  InfoIconLogo,
} from "./IconStyles";
export {
  FaceBookIcon,
  InstaGramIcon,
  TwitteRIcon,
  LinkedinIcon,
  YoutubeIcon,
  GlobeIcon,
  HeartIcon,
  GreaterThanIcon,
  CrossButtonIcon,
  StarIconLogo,
  InfoIconLogo,
};
