export const langVariations = [
'Сторінка не знайдена',
'Page not found',
'Seite nicht gefunden',
'Pagina non trovata',
'Página no encontrada',
'Η σελίδα δεν βρέθηκε',
'Sidan kunde inte hittas',
'Sayfa Bulunamadı',
'Page introuvable',
'Az oldal nem találhatót',
'Pagina niet gevonden',
'Siden blev ikke fundet',
'Sivua ei löydy',
'Stránka nebyla nalezena',
'Page Mhux tinsab',
]