export const langVariations = [
    {id: '1', value: 'Сторінка не знайдена'},
    {id: '2', value: 'Page not found'},
    {id: '3', value: 'Seite nicht gefunden'},
    {id: '4', value: 'Pagina non trovata'},
    {id: '5', value: 'Página no encontrada'},
    {id: '6', value: 'Η σελίδα δεν βρέθηκε'},
    {id: '7', value: 'Sidan kunde inte hittas'},
    {id: '8', value: 'Sayfa Bulunamadı'},
    {id: '9', value: 'Page introuvable'},
    {id: '10', value: 'Az oldal nem találhatót'},
    {id: '11', value: 'Pagina niet gevonden'},
    {id: '12', value: 'Siden blev ikke fundet'},
    {id: '13', value: 'Sivua ei löydy'},
    {id: '14', value: 'Stránka nebyla nalezena'},
    {id: '15', value: 'Page Mhux tinsab'},
]